version: "3.7"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.8
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
  web:
    build: .
    command: ./service
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - NAME=web
      - PORT=80
      - NEXT_URL=http://service1/
    ports:
      - "80:80"
    links:
      - jaeger
      - service1
  service1:
    build: .
    command: ./service
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - NAME=service1
      - PORT=80
      - NEXT_URL=http://service2/
    links:
      - jaeger
      - service2
  service2:
    build: .
    command: ./service
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - NAME=service2
      - PORT=80
      - NEXT_URL=http://service3/
    links:
      - jaeger
      - service3
  service3:
    build: .
    command: ./service
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - NAME=service3
      - PORT=80
      - NEXT_URL=https://api.github.com/users/aablinov
    links:
      - jaeger